baseURL: "https://master--marcopoianids.netlify.app/"
languageCode: en-us
title: Marco Poiani | Data Science
theme: PaperMod

params: 
  homeInfoParams: 
    Title: Hi There ğŸ‘‹, 
    Content: 
    " I am Marco Poiani, a master's student in Data Science ğŸ“ˆ at the University of Pisa. ğŸ« 
      I use this website as a personal archive for storing my projects and notes and tracking my journey as a student. ğŸ“"

  socialIcons: 
    - name: linkedin
      url: "https://www.linkedin.com/in/marco-poiani/"
    - name: github
      url: "https://github.com/MarcoPoiani00"
      
menu:
  main:
    - identifier: "Projects"
      name: "Projects"
      url: "/projects/"
      weight: 10
    - identifier: "Notes"
      name: "Notes"
      url: "/notes/"
      weight: 20
    - identifier: "RÃ¨sumÃ¨"
      name: "RÃ¨sumÃ¨"
      url: "/rÃ¨sumÃ¨/"
      weight: 30
