baseURL: "https://master--marcopoianids.netlify.app/"
languageCode: en-us
title: Marco Poiani | Data Science
theme: PaperMod

params: 
  homeInfoParams: 
    Title: Hi There ğŸ‘‹, 
    Content: 
    " I am Marco Poiani, a master's student in Data Science ğŸ“ˆ at the University of Pisa. ğŸ« 
      I use this website as a personal archive for storing my projects and notes and tracking my journey as a student. ğŸ“"

  socialIcons: 
    - name: linkedin
      url: "http://linkedin.com"
    - name: github
      url: "http://github.com"
      
menu:
  main:
    - identifier: "RÃ¨sumÃ¨"
      name: "RÃ¨sumÃ¨"
      url: "/rÃ¨sumÃ¨/"
      weight: 10

    - identifier: "Notes"
      name: "Notes"
      url: "/notes/"
      weight: 20

    - identifier: "Archives"
      name: "Archives"
      url: "/archives/"
      weight: 30
